### N-Grams

In [2]:
import pandas as pd


In [3]:
messages = pd.read_csv('SMSSpamCollection.csv', sep='\t',names=['label', 'message'])

In [4]:
import nltk
import re
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords

Using Lemmatization

In [7]:
from nltk.stem import WordNetLemmatizer

In [8]:
lemmatizer = WordNetLemmatizer()

In [9]:
corpus = []
for i in range(0,len(messages)):    
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i]) #Remove special characters
    review = review.lower() #Change to lower case
    review = review.split()
    review = [lemmatizer.lemmatize(lines) for lines in review if lines not in stopwords.words('english')] #Removing stopwords and stemming
    review = ' '.join(review)
    corpus.append(review)

In [10]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

Take top most occuring words using max_features

In [12]:
tfidf = TfidfVectorizer(max_features=100)

In [13]:
X = tfidf.fit_transform(corpus).toarray()

In [14]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(5572, 100))

In [17]:
exp = pd.DataFrame(X)

In [18]:
exp.to_csv()

',0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99\r\n0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.43424217191172815,0.0,0.0,0.46120459127324104,0.5440098522270297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.550252071147209,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0\r\n1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0

In [19]:
import numpy as np

In [20]:
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda X:"%.3g" % X))

In [21]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [22]:
tfidf.vocabulary_

{'go': np.int64(23),
 'great': np.int64(27),
 'got': np.int64(26),
 'wat': np.int64(89),
 'ok': np.int64(58),
 'free': np.int64(19),
 'win': np.int64(93),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(68),
 'already': np.int64(0),
 'think': np.int64(80),
 'life': np.int64(39),
 'hey': np.int64(30),
 'week': np.int64(91),
 'back': np.int64(6),
 'like': np.int64(40),
 'still': np.int64(73),
 'send': np.int64(70),
 'friend': np.int64(20),
 'prize': np.int64(63),
 'claim': np.int64(10),
 'call': np.int64(7),
 'mobile': np.int64(49),
 'co': np.int64(11),
 'home': np.int64(32),
 'want': np.int64(88),
 'today': np.int64(82),
 'cash': np.int64(9),
 'day': np.int64(15),
 'reply': np.int64(65),
 'www': np.int64(96),
 'right': np.int64(66),
 'take': np.int64(75),
 'time': np.int64(81),
 'message': np.int64(46),
 'com': np.int64(12),
 'oh': np.int64(57),
 'yes': np.int64(99),
 'make': np.int64(44),
 'way': np.int64(90),
 'dont': np.int64(17),
 'miss': np.int64(48),
 'ur': np.int64(

With ngrams

In [23]:
tfidf = TfidfVectorizer(max_features=100, ngram_range=(2,2))
X = tfidf.fit_transform(corpus).toarray()

In [24]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [25]:
tfidf.vocabulary_

{'free entry': np.int64(33),
 'claim call': np.int64(16),
 'call claim': np.int64(3),
 'claim code': np.int64(17),
 'free call': np.int64(32),
 'chance win': np.int64(15),
 'txt word': np.int64(89),
 'let know': np.int64(54),
 'please call': np.int64(68),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'first time': np.int64(31),
 'like lt': np.int64(55),
 'sorry call': np.int64(80),
 'call later': np.int64(8),
 'ur awarded': np.int64(90),
 'hi hi': np.int64(47),
 'call customer': np.int64(4),
 'customer service': np.int64(24),
 'guaranteed cash': np.int64(43),
 'cash prize': np.int64(14),
 'po box': np.int64(70),
 'trying contact': np.int64(86),
 'draw show': np.int64(29),
 'show prize': np.int64(79),
 'prize guaranteed': np.int64(74),
 'guaranteed call': np.int64(42),
 'valid hr': np.int64(95),
 'selected receive': np.int64(76),
 'private account': np.int64(72),
 'account statement': np.int64(0),
 'statement show': np.int64(82),
 'call identifier': np.int64(5),
 'identifier code':